spring:
  datasource:
    url: jdbc:h2:mem:cicdtest
    username: cicdtest
    password: cicdtest
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #     show_sql: true
        format_sql: true
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 2000

#trace < debug < info < warn < error
logging.level:
  root:  info
#  org.hibernate.SQL: debug
#  org.hibernate.type: trace